# Tiedonkäsittely Pythonilla (4 op)
### Tekijä: Roni Pihajoki
Lisätään tarvittavat kirjastot & datasetti käyttöön

In [33]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df_roni = pd.read_csv('WorkPlaceSatisfactionSurveyData.csv', encoding='utf-8')

## Miltä datasetti näyttää, mitä se pitää sisällään ja montako riviä/saraketta siinä on
Ensin on tuloste rivien & sarakkeiden määristä <br>
Sen jälkeen on tuloste taulukon kolmesta ensimmäisestä rivistä <br>
Tästä näemme sarakeotsikot & esimerkit arvoista, joita taulukko sisältää <br>
Tämän pohjalta saamme ajatuksen, mitä dataa meillä on ja mitä kaikkea voimme sillä tehdä <br>

In [34]:
print("Rivien lukumäärä: ",df_roni.shape[0])
print("Sarakkeiden lukumäärä: ",df_roni.shape[1])
print()
df_roni.head(3)

Rivien lukumäärä:  82
Sarakkeiden lukumäärä:  16

,number,gender,age,family,education,years_of_service,salary,sat_management,sat_colleques,sat_workingEnvironment,sat_salary,sat_tasks,holidayCabin,gym,muscleCare,healtcare
0,1,1,38,1,1.0,22.0,3587,3,3.0,3,3,3,NaN,NaN,NaN,NaN
1,2,1,29,2,2.0,10.0,2963,1,5.0,2,1,3,NaN,NaN,NaN,NaN
2,3,1,30,1,1.0,7.0,1989,3,4.0,1,1,3,NaN,NaN,NaN,1.0

# Datan käsittely
## Projektin esittely
Minulle tuli seuraavat taustamuuttujat käsiteltäväksi:
- Education (Sarake E) // Luokkamuuttuja
- Salary (Sarake G) // Numeerinen muuttuja

Sat_sarakkeet ovat "tyytyväisyys" sarakkeita<br>
- sat_management // Tämä kertoo kuinka tyytyväisiä johdosta ollaan
- sat_colleques // Tämä kertoo kuinka tyytyväisiä kolleegoista ollaan
- sat_workingEnvironment // Tämä kertoo kuinka tyytyväisiä työympäristöön ollaan
- sat_salary // Tämä kertoo kuinka tyytyväisiä palkkaan ollaan
- sat_tasks // Tämä kertoo kuinka tyytyväisiä työtehtäviin ollaan

Projektissa on ideana että käsitellään ensin jokainen taustamuuttuja ja sat_muuttuja erikseen<br>
(esimerkiksi palkan keskiarvo, korkein palkka tai matalin palkka)<br>
Kun yksittäis analysointi on valmista, alamme tutkimaan taustamuuttujia ja sat_muuttujia yhdessä<br>
(esimerkiksi miten korkeimman palkan saaja kokee tyytyväisyytensä työympäristöön)<br>
Yhteensä tehdään siis 10 yhdistelmä analysointia ja 7 erillistä muuttuja kohtaista analysointia<br>

## Muuttujien arvojen selvennys
Education (Korkein suoritettu tutkinto):
- 1 = peruskoulu tutkinto
- 2 = toisen asteen tutkinto
- 3 = Kandidaatin tutkinto
- 4 = Maisterin tutkinto

Salary:
- Kuukauden palkka euroina

sat_muuttujat:
- Asteikolla 1-5
- 1 tarkoittaa erittäin tyytymätöntä
- 5 tarkoittaa erittäin tyytyväistä

## Taulukon siistiminen
Poistetaan taulukosta meille turhat sarakkeet käyttäen .drop komentoa<br>
1. Tulostetaan tämän hetkisten sarakkeiden nimet
2. Poistetaan sieltä 4 viimeistä saraketta, joita me emme käytä analyysissämme
3. Tulostetaan 3 ensimmäistä riviä uudestaan, josta näemme että sarakkeet on poistettu oikein

In [35]:
df_roni.columns

Index(['number', 'gender', 'age', 'family', 'education', 'years_of_service',
       'salary', 'sat_management', 'sat_colleques', 'sat_workingEnvironment',
       'sat_salary', 'sat_tasks', 'holidayCabin', 'gym', 'muscleCare',
       'healtcare'],
      dtype='str')

In [36]:
df_roni = df_roni.drop(columns=['holidayCabin', 'gym', 'muscleCare', 'healtcare'])

In [37]:
df_roni.head(3)

,number,gender,age,family,education,years_of_service,salary,sat_management,sat_colleques,sat_workingEnvironment,sat_salary,sat_tasks
0,1,1,38,1,1.0,22.0,3587,3,3.0,3,3,3
1,2,1,29,2,2.0,10.0,2963,1,5.0,2,1,3
2,3,1,30,1,1.0,7.0,1989,3,4.0,1,1,3

# Taustamuuttujat

### Education Luokkamuuttuja

Tarkastellaan ensin perusteita<br>
Mikä on korkein henkilön suorittama tutkinto<br>
- Peruskoulu tutkintoja korkeimpana suorituksena on 27 henkilöllä<br>
- Toisen asteen tutkintoja korkeimpana suorituksena on 30 henkilöllä<br>
- Kanditattti tason tutkintoja korkeimpana suorituksena on 22 henkilöllä<br>
- Maisteri tason tutkintoja koirkaimpana suorituksena on 2 henkilöllä

In [48]:
print(df_roni['education'].value_counts())

education
2.0    30
1.0    27
3.0    22
4.0     2
Name: count, dtype: int64

Koulutusten keskiarvo sekä mediaani ovat 2 (tai ainakin hyvin lähellä 0.0123 erolla)<br>
Poikkkeama normaaliarvosta on 0.84<br>
Varianssin hajonta keskiarvosta 2 on 0.71<br>

In [50]:
keskiarvo = df_roni['education'].mean()
mediaani = df_roni['education'].median()
poikkeama = df_roni['education'].std()
varianssi = df_roni['education'].var()

print("Koulutusten keskiarvo on  {:.4f}".format(keskiarvo))
print("Koulutusten mediaani on  {:.0f}".format(mediaani))
print("Koulutusten poikkeama on  {:.2f}".format(poikkeama))
print("Koulutusten varianssi on  {:.2f}".format(varianssi))

Koulutusten keskiarvo on  1.9877
Koulutusten mediaani on  2
Koulutusten poikkeama on  0.84
Koulutusten varianssi on  0.71

### Salary numeerinen muttuja

# Sat_Muuttujat

### sat_management

### sat_colleques

### sat_workingEnvironment

### sat_salary

### sat_tasks

# Taustamuuttujien & Sat_muuttujien ristiin vertailu