In [1]:
import pandas as pd

df=pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]],['r0','r1','r2'],['c0','c1','c2'])

# see https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html

In [2]:
df

    c0  c1  c2
r0   1   2   3
r1   4   5   6
r2   7   8   9

In [3]:
df[['c0', 'c1']]   # selecting columns "c0" and "c1". This we have seen already. Note the use of square brackets.

    c0  c1
r0   1   2
r1   4   5
r2   7   8

## Indexers loc and iloc

* loc operates with index labels
* iloc operates with index numeric numbers

#### Case Loc

In [4]:
df.loc[['r0','r2'],['c0','c2']]                   # Rows first then columns

    c0  c2
r0   1   3
r2   7   9

In [5]:
df.loc[['r0','r2'],:]

    c0  c1  c2
r0   1   2   3
r2   7   8   9

In [6]:
df.loc[:,['c0','c2']]

    c0  c2
r0   1   3
r1   4   6
r2   7   9

#### Case iloc

In [7]:
df.iloc[[0,2],[0,2]]
# df.iloc[[0,2],['c0', 'c2']] => Does not work, requires numerical index also for columns!

    c0  c2
r0   1   3
r2   7   9

In [8]:
df.iloc[[0,2],:]

    c0  c1  c2
r0   1   2   3
r2   7   8   9

In [9]:
df.iloc[:,[0,2]]

    c0  c2
r0   1   3
r1   4   6
r2   7   9

In [10]:
df.iloc[:,[0,2]]=1

In [11]:
df

    c0  c1  c2
r0   1   2   1
r1   1   5   1
r2   1   8   1

We can also create new columns into Pandas dataframe (table) easily. Here by calculating the sum of columns "c1" and "c2" and saving the result in new column called "c3"

In [12]:
df['c3'] = df['c1'] + df['c2']

In [13]:
df

    c0  c1  c2  c3
r0   1   2   1   3
r1   1   5   1   6
r2   1   8   1   9

## Selecting/Filtering

In [14]:
B=[False,True, True]

In [15]:
df[B]

    c0  c1  c2  c3
r1   1   5   1   6
r2   1   8   1   9

In [16]:
df=pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]],['r0','r1','r2'],['c0','c1','c2'])

In [17]:
df

    c0  c1  c2
r0   1   2   3
r1   4   5   6
r2   7   8   9

In [18]:
df['c0']>3

r0    False
r1     True
r2     True
Name: c0, dtype: bool

In [19]:
type(df['c0']>3)

pandas.core.series.Series

In [20]:
df[df['c0']>3]

    c0  c1  c2
r1   4   5   6
r2   7   8   9

In [21]:
df.loc[df['c0']>3,'c0']

r1    4
r2    7
Name: c0, dtype: int64

In [22]:
df.iloc[(df['c0']>3).values,0]

r1    4
r2    7
Name: c0, dtype: int64